swagger: "2.0"
info:
  title: beego Test API
  description: |
    beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /user-service/v1
paths:
  /admin/users/:
    get:
      tags:
      - admin/users
      summary: Get Users
      description: |-
        Get Users
        <br>
      operationId: UserAdminController.Get Users
      parameters:
      - in: query
        name: limit
        description: limit of this request
        type: integer
        format: int64
      - in: query
        name: page
        description: page of this request
        type: integer
        format: int64
      responses:
        "200":
          description: ""
        "403":
          description: ""
tags:
- name: admin/users
  description: |
    Operations about object
